#!/bin/sh

for file in `ls html/`;
do
    echo $file

    enb_info="{"
    enb_info+=`sed -E -n 's/.*eNB ID ([0-9]*).*/"enb_id": \1,/p' ./html/$file`
    enb_info+=`sed -E -n 's/.*MCC \/ MNC \/ Region.*>([0-9]*) \/ ([0-9]*) \/ ([0-9]*)<.*/"mcc": \1, "mnc": \2, "region": \3,/p' html/$file`
    enb_info+=`tail -n 1 html/$file | sed -E -n 's/\s*(.*),(.*)/"lat":\1,"long":\2/p'`
    enb_info+="}"
    echo $enb_info > ./json/enb_info.json
    # extract the html content into a json file
    cat ./html/$file | pup 'table[id^=detailsTable] json{}' > ./json/out.json

    # improve said json file
    cat ./json/out.json | jq '[.[] | {name: .children[0].children[0].children[0].text,
    properties : .children[1].children}]' > ./json/parsed.json

    # Process the output and saves it to the final JSON
    # python ./fine_tunning.py
done
